// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzi-O9M1mD1UD-_U3yTOkhvIDWG-AVAeM',
    appId: '1:617497615103:web:46a5db59f73f50973dcaca',
    messagingSenderId: '617497615103',
    projectId: 'opendev-labs-syncstack',
    authDomain: 'opendev-labs-syncstack.firebaseapp.com',
    storageBucket: 'opendev-labs-syncstack.firebasestorage.app',
    measurementId: 'G-T8W1ZVF7Q4',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyBzi-O9M1mD1UD-_U3yTOkhvIDWG-AVAeM',
    appId: '1:617497615103:web:46a5db59f73f50973dcaca',
    messagingSenderId: '617497615103',
    projectId: 'opendev-labs-syncstack',
    storageBucket: 'opendev-labs-syncstack.firebasestorage.app',
  );
}