name: syncstack
base: core22
version: '2.1.0'
title: SyncStack
summary: Enterprise GitHub Synchronization Engine
description: |
  A high-performance, minimalist desktop client for professional developers.
  Designed with the Antigravity IDE aesthetic: a high-contrast Matt-Black foundation
  with vibrant Neon-Green accents.

  Core Features:
  - Antigravity Matt-Black/Neon-Green aesthetic
  - SVG-native iconography for infinite scalability
  - Python-powered intelligent synchronization
  - Zero-bloat native performance (Flutter)
  - Seamless IPC-based bridge to GH Engine (Python)

grade: stable
confinement: strict

website: https://github.com/opendev-labs/syncstack
contact: https://github.com/opendev-labs/syncstack/issues
issues: https://github.com/opendev-labs/syncstack/issues
source-code: https://github.com/opendev-labs/syncstack

parts:
  syncstack-desktop:
    source: build/linux/x64/release/bundle
    plugin: dump
    stage-packages:
      - python3
      - python3-requests
      - libgtk-3-0
      - libpcre3
      - libblkid1
      - liblzma5
      - libgcrypt20
      - libsystemd0
  desktop-metadata:
    plugin: dump
    source: .
    organize:
      snap/gui/syncstack.desktop: usr/share/applications/syncstack.desktop
      assets/metadata/syncstack.metainfo.xml: usr/share/metainfo/syncstack.metainfo.xml
      snap/gui/logo.svg: usr/share/icons/hicolor/scalable/apps/syncstack.svg

apps:
  syncstack:
    command: syncstack
    desktop: usr/share/applications/syncstack.desktop
    extensions: [gnome]
    plugs:
      - network
      - home
      - unity7
